version: "3"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
      - mongodb
  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: checkpoint
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017